### ISSUE TITLE
New device "DC11EP"

### ISSUE THREAD

**Issue by AlexObukhoff** [Limych/py-beward#100]
Device ID as it was detected by `py-beward` library: DC11EP

Web-link to official device's description: archive model https://club.cnews.ru/blogs/entry/beward_predstavlyaet_vyzyvnaya_panel_dc11eps
https://mcgrp.ru/files/viewer/616898/1#navigate_bar
https://safe-logic.ru/catalog/domofoniya/ip-videodomofon-dc11ep

DC11EP
firmware: 3.1.7.0.3.18.27
web interface: 2.1.3.8(20180228)

**Comment by AlexObukhoff** [comment]
![image](https://user-images.githubusercontent.com/5196879/193460327-3cb6814f-4c1c-47e8-adf6-218b13b46947.png)

**Comment by Limych** [comment]
Thanks :heart:
