### ISSUE TITLE
DSN23215PS

### ISSUE THREAD

**Issue by Vugl78** [Limych/py-beward#132]
Device ID as it was detected by `py-beward` library: DSN23215PS

Web-link to official device's description: https://www.beward.ru/katalog/specoborudovanie/bezopasny-region/vyzyvnaya-panel-ds91406m/

**Comment by ha30region** [comment]
Web-link to official device's description: https://www.beward.ru/katalog/specoborudovanie/bezopasny-region/vyzyvnaya-panel-dsn23215ps/

**Comment by ha30region** [comment]
Прошу добавить вызывную панель DSN23215PS в библиотеку.

**Comment by Vugl** [comment]
![a7b28-clip-30kb](https://github.com/Limych/py-beward/assets/12271773/1e1c5b2b-bc57-4e21-916b-79297dbfc349)
Not worked ((
