### ISSUE TITLE
Unknown device "S06A"

### ISSUE THREAD

**Issue by Limych** [Limych/py-beward#3]
Hi,
In the notifications I have this messages: 

> "Invalid config - The following components and platforms could not be set up: beward - Please check your config."

 and 

> "Beward device Initialization Failure - Error: Unknown device "**S06A**" - Please contact the developers of the Beward library to solve this problem."

 How to fix it?

_Originally posted by @bobsilesia in https://github.com/Limych/py-beward/issues/2#issuecomment-557877470_

**Comment by Limych** [comment]
@bobsilesia, Please tell me your device model and I will add it to the driver settings.

**Comment by bobsilesia** [comment]
Hi Limych,
This is Beward with firmware from Polish distributor **SAFE**
Device model (system info): **S06A** 
Oryginal hardware: **DS06AP-3L**

ps
Please add this device here as well:
https://github.com/Limych/ha-beward

**Comment by Limych** [comment]
Fixed
