### ISSUE TITLE
Beward device Initialization Failure

### ISSUE THREAD

**Issue by Sergbmw** [Limych/py-beward#7]
## Checklist
- [ ] I updated the component to the latest version available

Beward device Initialization Failure
Error: Unknown device "None"
Please contact the developers of the Beward library to solve this problem.

## Version of the component

-->
Version: 6d40071

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce
This is the configuration I used:
```yaml

Add your configs here.

```

## Debug log

```text

Add your logs here.

```

## Expected behavior

_A clear and concise description of what you expected to happen._

## Additional context

Logger: homeassistant.setup
Source: custom_components/beward/__init__.py:133 
First occurred: 10:58:21 (1 occurrences) 
Last logged: 10:58:21

Error during setup of component beward
Traceback (most recent call last):
  File "/config/custom_components/beward/__init__.py", line 121, in setup
    stream=stream,
  File "/usr/local/lib/python3.7/site-packages/beward/__init__.py", line 55, in factory
    raise ValueError('Unknown device "%s"' % model)
ValueError: Unknown device "None"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/beward/__init__.py", line 133, in setup
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady

**Comment by Limych** [comment]
Please fill in the bug report fully in accordance with the provided template. In its current form, it is not possible to localize the error.
