### ISSUE TITLE
Unknown device "B102S"

### ISSUE THREAD

**Issue by KoToZoid** [Limych/py-beward#76]
**Is your feature request related to a problem? Please describe.**

I couldn't set up integration with the BE102S videocoder. 
https://www.beward.ru/katalog/ip-videoservery/videokodery-dekodery/ip-videokoder-b102s/
This device is used to turn any analog CCTV camera into an IP camera.

The device cannot be configured via "Add integration" and when manually configured via "configuration.yaml" the error 
"Unknown device "B102S" 
is visible in the list of integrations.

Also in the log you can see the following:

Logger: custom_components.beward
Source: custom_components/beward/__init__.py:173
Integration: Beward Integration ([documentation](https://github.com/Limych/ha-beward), [issues](https://github.com/Limych/ha-beward/issues))
First occurred: 17:04:12 (7 occurrences)
Last logged: 17:08:04
Unknown device "B102S"

**Describe the solution you'd like**

It would be great to add "B102S" to the list of supported devices.

**Describe alternatives you've considered**

Any workaround such as additional manual configuration also will be appreciated.

**Additional context**

Beward Integration "version": "1.1.18"

![image](https://user-images.githubusercontent.com/84103892/164985749-d72daf47-6901-4e2d-8046-5049fa4cc910.png)

![image](https://user-images.githubusercontent.com/84103892/164985784-436eec7c-1c95-45c9-8a6e-2dee3c1e93a7.png)

**Comment by Limych** [comment]
Ок, добавлю, спасибо.
