### ISSUE TITLE
DKS850100

### ISSUE THREAD

**Issue by celousov** [Limych/py-beward#87]
Device ID as it was detected by `py-beward` library:

Web-link to official device's description:

**Comment by celousov** [comment]
Beward DKS850100 worked!
and
Beward B4230RVZ worked
and Keno KN-DE205A2812BR worked

**Comment by celousov** [comment]
Beward DKS850100 rtsp://user:pass@yourip:554/av0_1 or 0_0
Beward B4230RVZ rtsp://user:pass@yourip:554/av0_1 or 0_0
Keno KN-DE205A2812BR rtsp://user:pass@yourip:554/ch01_sub.264?dev=1

**Comment by Limych** [comment]
Please open a separate issue for each device.  And complete the form in each issue.
